---
abstract: 'a simpler way to get and set the Value of a Widget'
author:
  - 'Herbert Breunung'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: ''
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Wx-Widget
no_index:
  directory:
    - inc
    - t
requires:
  Tie::Scalar: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tie-Wx-Widget
  license: http://www.netvibes.com/privatepage/1#Perl
version: 0.01
