---
# http://module-build.sourceforge.net/META-spec.html
name:         Tie-Wx-Widget
version:      0.2
version_from: Tie::Wx::Widget.pm
abstract:     a simpler way to get and set the Value of a Widget
installdirs:  site
distribution_type: module
author:       Herbert Breunung <lichtkind@cpan.org>
license:      perl
build_requires:
  Wx: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
generated_by: ''
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
  Tie::Scalar: 0
  Wx: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tie-Wx-Widget
  license: http://www.netvibes.com/privatepage/1#Perl
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
